# Generated by Django 4.0.1 on 2022-01-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='N_category',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'N_catagory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='N_category_detail',
            fields=[
                ('cd_id', models.AutoField(primary_key=True, serialize=False)),
                ('cd_name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'N_catagory_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='N_content',
            fields=[
                ('nc_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'N_content',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='N_summarization',
            fields=[
                ('ns_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'N_summarization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('n_id', models.IntegerField(primary_key=True, serialize=False)),
                ('n_title', models.CharField(max_length=1024)),
                ('nd_img', models.CharField(max_length=1024)),
                ('o_link', models.CharField(max_length=768, unique=True)),
            ],
            options={
                'db_table': 'News',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Press',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.TextField()),
            ],
            options={
                'db_table': 'Press',
                'managed': False,
            },
        ),
    ]
