# Generated by Django 4.0.1 on 2022-01-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NCategory',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=5, unique=True)),
            ],
            options={
                'db_table': 'N_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NCategoryDetail',
            fields=[
                ('cd_id', models.AutoField(primary_key=True, serialize=False)),
                ('cd_name', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'N_category_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NContent',
            fields=[
                ('nc_id', models.AutoField(primary_key=True, serialize=False)),
                ('n_content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'N_content',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NSummarization',
            fields=[
                ('ns_id', models.AutoField(primary_key=True, serialize=False)),
                ('ns_content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'N_summarization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PyboNCategory',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'pybo_n_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PyboNCategoryDetail',
            fields=[
                ('cd_id', models.AutoField(primary_key=True, serialize=False)),
                ('cd_name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'pybo_n_category_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PyboNContent',
            fields=[
                ('nc_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'pybo_n_content',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PyboNews',
            fields=[
                ('n_id', models.IntegerField(primary_key=True, serialize=False)),
                ('n_title', models.CharField(max_length=1024)),
                ('nd_img', models.CharField(max_length=1024)),
                ('o_link', models.CharField(max_length=768, unique=True)),
            ],
            options={
                'db_table': 'pybo_news',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PyboNSummarization',
            fields=[
                ('ns_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'pybo_n_summarization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PyboPress',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.TextField()),
            ],
            options={
                'db_table': 'pybo_press',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='N_category',
        ),
        migrations.DeleteModel(
            name='N_category_detail',
        ),
        migrations.DeleteModel(
            name='N_content',
        ),
        migrations.DeleteModel(
            name='N_summarization',
        ),
    ]
